name: Automatically update flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update sourcing information
        env:
          OWNER: bernardo-bruning
          REPO: ollama-copilot
        run: |
          nix run nixpkgs#nix-prefetch-github -- --json $OWNER $REPO > sourcing_new.json
          mv sourcing_new.json sourcing.json

      - name: Update flake
        run: |
          nix flake update

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sourcing.json
          git add flake.lock
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "build(auto): update"
            git push
          else
            echo "No changes to commit"
          fi
